<div class="container-center">
    <img src="images/ever-framework-logo.png" alt="Ever Framework">
    <h1>Bem-vindo ao <strong>Ever Framework</strong></h1>
    <p>
        Para uma melhor utilização de todos os recursos, <br />
        consulte a documentação contida no repositório:<br />
        <a href="https://github.com/everson-da-luz/ever-framework" target="blank">https://github.com/everson-da-luz/ever-framework</a>
    </p>
    <p>
        <small>
            Ever Framework - desenvolvido por 
            <a href="http://www.eversondaluz.com.br" target="blank">www.eversondaluz.com.br</a>
            - 2016
        </small>
    </p>
</div>